import "./globals.css";
import localFont from 'next/font/local';
import ClientLayout from '@/components/ClientLayout';

const hostGrotesk = localFont({
  src: [
    {
      path: '../../public/Font/HostGrotesk-VariableFont_wght.ttf',
      style: 'normal',
    },
    {
      path: '../../public/Font/HostGrotesk-Italic-VariableFont_wght.ttf',
      style: 'italic',
    },
  ],
  variable: '--font-host-grotesk',
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${hostGrotesk.variable}`}>
      <body>
        <ClientLayout>
          {children}
        </ClientLayout>
      </body>
    </html>
  );
}
